name: bn_api
description: Binance API
version: 0.1.16
homepage: http://github.com/meoook/bn_api

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.5
  web_socket_channel: ^2.2.0

dev_dependencies:
  test: ^1.21.6
